-- VEFFLOKKAR (Krónu-stíll): sjálfstætt flokkakerfi við hliðina á kassaflokkunum (product_group
-- 10/20/30 stýrir áfram tökkunum á kassanum og er ÓSNERT). Tréð er raunveruleg flokkun Krónunnar
-- af kronan.is/voruurval (ágúst 2026) + "Vinsælar vörur" að ósk Fannars; undirflokka-slóðir eru
-- yfirslóð--undirheiti. Vara fær vefflokk á vöruspjaldinu (products.web_category).
set search_path = shop, public;

create table if not exists shop.web_categories (
  slug        text primary key,
  name        text not null,
  parent_slug text references shop.web_categories(slug),
  sort        int  not null default 0
);

alter table shop.products
  add column if not exists web_category text references shop.web_categories(slug);

insert into shop.web_categories (slug, name, parent_slug, sort) values
  ('vinsaelar-vorur', 'Vinsælar vörur', null, 10),
  ('vinsaelar-vorur--mest-seldu-vorurnar', 'Mest seldu vörurnar', 'vinsaelar-vorur', 1),
  ('vinsaelar-vorur--tilbod-vikunnar', 'Tilboð vikunnar', 'vinsaelar-vorur', 2),
  ('vinsaelar-vorur--nyjar-vorur', 'Nýjar vörur', 'vinsaelar-vorur', 3),
  ('avextir', 'Ávextir', null, 20),
  ('avextir--bananar-perur-og-epli', 'Bananar, perur og epli', 'avextir', 1),
  ('avextir--melonur-og-ber', 'Melónur og ber', 'avextir', 2),
  ('avextir--sudraenir-og-sitrusavextir', 'Suðrænir og sítrusávextir', 'avextir', 3),
  ('avextir--steinaldin', 'Steinaldin', 'avextir', 4),
  ('graenmeti', 'Grænmeti', null, 30),
  ('graenmeti--kal-og-salat', 'Kál og salat', 'graenmeti', 1),
  ('graenmeti--kartoflur-og-rotargraenmeti', 'Kartöflur og rótargrænmeti', 'graenmeti', 2),
  ('graenmeti--kryddjurtir', 'Kryddjurtir', 'graenmeti', 3),
  ('graenmeti--sveppir-og-laukur', 'Sveppir og laukur', 'graenmeti', 4),
  ('graenmeti--tomatar-paprika-og-agurkur', 'Tómatar, paprika og agúrkur', 'graenmeti', 5),
  ('graenmeti--annad-graenmeti', 'Annað grænmeti', 'graenmeti', 6),
  ('kjot', 'Kjöt', null, 40),
  ('kjot--lambakjot', 'Lambakjöt', 'kjot', 1),
  ('kjot--nautakjot', 'Nautakjöt', 'kjot', 2),
  ('kjot--svinakjot', 'Svínakjöt', 'kjot', 3),
  ('kjot--folalda-og-hrossakjot', 'Folalda- og hrossakjöt', 'kjot', 4),
  ('kjot--kjuklingur-og-fuglakjot', 'Kjúklingur og fuglakjöt', 'kjot', 5),
  ('kjot--reykt-og-saltad-kjot', 'Reykt og saltað kjöt', 'kjot', 6),
  ('kjot--pylsur-budingar-og-bjugu', 'Pylsur, búðingar og bjúgu', 'kjot', 7),
  ('kjot--slatur-og-thorramatur', 'Slátur og þorramatur', 'kjot', 8),
  ('fiskur', 'Fiskur', null, 50),
  ('fiskur--ferskur-fiskur', 'Ferskur fiskur', 'fiskur', 1),
  ('fiskur--fiskrettir', 'Fiskréttir', 'fiskur', 2),
  ('fiskur--hardfiskur', 'Harðfiskur', 'fiskur', 3),
  ('fiskur--skelfiskur', 'Skelfiskur', 'fiskur', 4),
  ('fiskur--humar-og-raekjur', 'Humar og rækjur', 'fiskur', 5),
  ('mjolkurvorur-og-egg', 'Mjólkurvörur og egg', null, 60),
  ('mjolkurvorur-og-egg--mjolk', 'Mjólk', 'mjolkurvorur-og-egg', 1),
  ('mjolkurvorur-og-egg--rjomi', 'Rjómi', 'mjolkurvorur-og-egg', 2),
  ('mjolkurvorur-og-egg--ostar', 'Ostar', 'mjolkurvorur-og-egg', 3),
  ('mjolkurvorur-og-egg--smjor-og-smjorliki', 'Smjör og smjörlíki', 'mjolkurvorur-og-egg', 4),
  ('mjolkurvorur-og-egg--skyr-og-jogurt', 'Skyr og jógúrt', 'mjolkurvorur-og-egg', 5),
  ('mjolkurvorur-og-egg--syrdur-rjomi', 'Sýrður rjómi', 'mjolkurvorur-og-egg', 6),
  ('mjolkurvorur-og-egg--jurtamjolkurvara', 'Jurtamjólkurvara', 'mjolkurvorur-og-egg', 7),
  ('mjolkurvorur-og-egg--kaldar-sosur-og-medlaeti', 'Kaldar sósur og meðlæti', 'mjolkurvorur-og-egg', 8),
  ('mjolkurvorur-og-egg--egg', 'Egg', 'mjolkurvorur-og-egg', 9),
  ('braud-kokur-og-kex', 'Brauð, kökur og kex', null, 70),
  ('braud-kokur-og-kex--nybakad', 'Nýbakað', 'braud-kokur-og-kex', 1),
  ('braud-kokur-og-kex--braud', 'Brauð', 'braud-kokur-og-kex', 2),
  ('braud-kokur-og-kex--samlokubraud', 'Samlokubrauð', 'braud-kokur-og-kex', 3),
  ('braud-kokur-og-kex--rugbraud-flatkokur-og-skonsur', 'Rúgbrauð, flatkökur og skonsur', 'braud-kokur-og-kex', 4),
  ('braud-kokur-og-kex--hamborgara-og-pylsubraud', 'Hamborgara- og pylsubrauð', 'braud-kokur-og-kex', 5),
  ('braud-kokur-og-kex--hrokkbraud-ris-og-maiskokur', 'Hrökkbrauð, rís- og maískökur', 'braud-kokur-og-kex', 6),
  ('braud-kokur-og-kex--pizzabotnar', 'Pizzabotnar', 'braud-kokur-og-kex', 7),
  ('braud-kokur-og-kex--glutenlaust', 'Glútenlaust', 'braud-kokur-og-kex', 8),
  ('braud-kokur-og-kex--kokur-og-saetabraud', 'Kökur og sætabrauð', 'braud-kokur-og-kex', 9),
  ('braud-kokur-og-kex--kex', 'Kex', 'braud-kokur-og-kex', 10),
  ('a-braud', 'Á brauð', null, 80),
  ('a-braud--kjotalegg', 'Kjötálegg', 'a-braud', 1),
  ('a-braud--lax-og-silungur', 'Lax og silungur', 'a-braud', 2),
  ('a-braud--sild-og-kaviar', 'Síld og kavíar', 'a-braud', 3),
  ('a-braud--kaefa-og-pate', 'Kæfa og paté', 'a-braud', 4),
  ('a-braud--braudsalot', 'Brauðsalöt', 'a-braud', 5),
  ('a-braud--hnetusmjor-og-smuralegg', 'Hnetusmjör og smurálegg', 'a-braud', 6),
  ('a-braud--hummus', 'Hummus', 'a-braud', 7),
  ('a-braud--sulta', 'Sulta', 'a-braud', 8),
  ('eldamennskan', 'Eldamennskan', null, 90),
  ('eldamennskan--italia', 'Ítalía', 'eldamennskan', 1),
  ('eldamennskan--asia', 'Asía', 'eldamennskan', 2),
  ('eldamennskan--mexiko', 'Mexíkó', 'eldamennskan', 3),
  ('eldamennskan--hrisgrjon-kuskus-og-kinoa', 'Hrísgrjón, kúskús og kínóa', 'eldamennskan', 4),
  ('eldamennskan--olia-og-edik', 'Olía og edik', 'eldamennskan', 5),
  ('eldamennskan--baunir', 'Baunir', 'eldamennskan', 6),
  ('eldamennskan--sosur-sinnep-og-marineringar', 'Sósur, sinnep og marineringar', 'eldamennskan', 7),
  ('eldamennskan--pakkasupur-og-sosur', 'Pakkasúpur og -sósur', 'eldamennskan', 8),
  ('eldamennskan--nidursuduvara', 'Niðursuðuvara', 'eldamennskan', 9),
  ('eldamennskan--krydd-og-kraftur', 'Krydd og kraftur', 'eldamennskan', 10),
  ('bakstur', 'Bakstur', null, 100),
  ('bakstur--hveiti-mjol-og-sykur', 'Hveiti, mjöl og sykur', 'bakstur', 1),
  ('bakstur--bokunarvara', 'Bökunarvara', 'bakstur', 2),
  ('bakstur--sultugerd-budingar-hlaup-og-matarlim', 'Sultugerð, búðingar, hlaup og matarlím', 'bakstur', 3),
  ('bakstur--bakstursblondur-og-krem', 'Bakstursblöndur og krem', 'bakstur', 4),
  ('bakstur--bokunarkrydd-og-dropar', 'Bökunarkrydd og dropar', 'bakstur', 5),
  ('bakstur--bokunarpappir-og-form', 'Bökunarpappír og -form', 'bakstur', 6),
  ('morgunmatur-og-heilsubot', 'Morgunmatur og heilsubót', null, 110),
  ('morgunmatur-og-heilsubot--morgunmatur', 'Morgunmatur', 'morgunmatur-og-heilsubot', 1),
  ('morgunmatur-og-heilsubot--hnetur-og-frae', 'Hnetur og fræ', 'morgunmatur-og-heilsubot', 2),
  ('morgunmatur-og-heilsubot--thurrkadir-avextir', 'Þurrkaðir ávextir', 'morgunmatur-og-heilsubot', 3),
  ('morgunmatur-og-heilsubot--vitamin', 'Vítamín', 'morgunmatur-og-heilsubot', 4),
  ('morgunmatur-og-heilsubot--faedubotaefni', 'Fæðubótaefni', 'morgunmatur-og-heilsubot', 5),
  ('morgunmatur-og-heilsubot--orkustangir-og-skvisur', 'Orkustangir og -skvísur', 'morgunmatur-og-heilsubot', 6),
  ('morgunmatur-og-heilsubot--heilsa-og-vellidan', 'Heilsa og vellíðan', 'morgunmatur-og-heilsubot', 7),
  ('tilbunir-rettir', 'Tilbúnir réttir', null, 120),
  ('tilbunir-rettir--heitur-matur', 'Heitur matur', 'tilbunir-rettir', 1),
  ('tilbunir-rettir--rotisserie', 'Rotisserie', 'tilbunir-rettir', 2),
  ('tilbunir-rettir--kjuklingur', 'Kjúklingur', 'tilbunir-rettir', 3),
  ('tilbunir-rettir--kjotrettir', 'Kjötréttir', 'tilbunir-rettir', 4),
  ('tilbunir-rettir--fiskrettir', 'Fiskréttir', 'tilbunir-rettir', 5),
  ('tilbunir-rettir--graenmetisrettir-og-medlaeti', 'Grænmetisréttir og meðlæti', 'tilbunir-rettir', 6),
  ('tilbunir-rettir--pizzur-pasta-og-lasagna', 'Pizzur, pasta og lasagna', 'tilbunir-rettir', 7),
  ('tilbunir-rettir--supur-og-sosur', 'Súpur og sósur', 'tilbunir-rettir', 8),
  ('tilbunir-rettir--grytur-og-hradrettir', 'Grýtur og hraðréttir', 'tilbunir-rettir', 9),
  ('tilbunir-rettir--tilbuid-a-ferdinni', 'Tilbúið á ferðinni', 'tilbunir-rettir', 10),
  ('frystivara', 'Frystivara', null, 130),
  ('frystivara--avextir-og-graenmeti', 'Ávextir og grænmeti', 'frystivara', 1),
  ('frystivara--braud-og-saetabraud', 'Brauð og sætabrauð', 'frystivara', 2),
  ('frystivara--franskar', 'Franskar', 'frystivara', 3),
  ('frystivara--kjotliki', 'Kjötlíki', 'frystivara', 4),
  ('frystivara--sjavarfang', 'Sjávarfang', 'frystivara', 5),
  ('frystivara--kjot', 'Kjöt', 'frystivara', 6),
  ('frystivara--tilbunir-rettir', 'Tilbúnir réttir', 'frystivara', 7),
  ('frystivara--is-og-eftirrettir', 'Ís og eftirréttir', 'frystivara', 8),
  ('drykkir', 'Drykkir', null, 140),
  ('drykkir--avaxtasafar-og-theytingar', 'Ávaxtasafar og -þeytingar', 'drykkir', 1),
  ('drykkir--ithrottadrykkir', 'Íþróttadrykkir', 'drykkir', 2),
  ('drykkir--kaldir-kaffidrykkir', 'Kaldir kaffidrykkir', 'drykkir', 3),
  ('drykkir--lifstilsdrykkir', 'Lífstílsdrykkir', 'drykkir', 4),
  ('drykkir--vatn-og-kolsyrt-vatn', 'Vatn og kolsýrt vatn', 'drykkir', 5),
  ('drykkir--thykkni-saft-og-sider', 'Þykkni, saft og síder', 'drykkir', 6),
  ('drykkir--gosdrykkir', 'Gosdrykkir', 'drykkir', 7),
  ('drykkir--orkudrykkir', 'Orkudrykkir', 'drykkir', 8),
  ('drykkir--lettol', 'Léttöl', 'drykkir', 9),
  ('drykkir--mocktails-bubblur-og-0-drykkir', 'Mocktails, búbblur og 0% drykkir', 'drykkir', 10),
  ('heitir-drykkir', 'Heitir drykkir', null, 150),
  ('heitir-drykkir--kaffi', 'Kaffi', 'heitir-drykkir', 1),
  ('heitir-drykkir--te', 'Te', 'heitir-drykkir', 2),
  ('heitir-drykkir--kako', 'Kakó', 'heitir-drykkir', 3),
  ('laugardags', 'Laugardags', null, 160),
  ('laugardags--hnetur-og-nasl', 'Hnetur og nasl', 'laugardags', 1),
  ('laugardags--snakk', 'Snakk', 'laugardags', 2),
  ('laugardags--saelgaeti', 'Sælgæti', 'laugardags', 3),
  ('laugardags--sukkuladi', 'Súkkulaði', 'laugardags', 4),
  ('laugardags--is-og-frostpinnar', 'Ís og frostpinnar', 'laugardags', 5),
  ('bornin', 'Börnin', null, 170),
  ('bornin--barnamatur', 'Barnamatur', 'bornin', 1),
  ('bornin--barnaservara', 'Barnasérvara', 'bornin', 2),
  ('bornin--barnasnyrtivara', 'Barnasnyrtivara', 'bornin', 3),
  ('bornin--blautklutar', 'Blautklútar', 'bornin', 4),
  ('bornin--bleiur', 'Bleiur', 'bornin', 5),
  ('bornin--leikfong', 'Leikföng', 'bornin', 6),
  ('heimilid', 'Heimilið', null, 180),
  ('heimilid--thvottur', 'Þvottur', 'heimilid', 1),
  ('heimilid--thrif', 'Þrif', 'heimilid', 2),
  ('heimilid--plastvara-og-alpappir', 'Plastvara og álpappír', 'heimilid', 3),
  ('heimilid--heimilisvorur', 'Heimilisvörur', 'heimilid', 4),
  ('heimilid--skreytingar-og-bordbunadur', 'Skreytingar og borðbúnaður', 'heimilid', 5),
  ('heimilid--blom-og-blomvendir', 'Blóm og blómvendir', 'heimilid', 6),
  ('heimilid--sottvarnir', 'Sóttvarnir', 'heimilid', 7),
  ('heimilid--baekur-og-timarit', 'Bækur og tímarit', 'heimilid', 8),
  ('snyrtivara', 'Snyrtivara', null, 190),
  ('snyrtivara--harumhirda', 'Hárumhirða', 'snyrtivara', 1),
  ('snyrtivara--hreinlaetisvara', 'Hreinlætisvara', 'snyrtivara', 2),
  ('snyrtivara--tannumhirda', 'Tannumhirða', 'snyrtivara', 3),
  ('snyrtivara--hudumhirda', 'Húðumhirða', 'snyrtivara', 4),
  ('snyrtivara--rakstur', 'Rakstur', 'snyrtivara', 5),
  ('snyrtivara--fordun', 'Förðun', 'snyrtivara', 6),
  ('snyrtivara--gjafakassar', 'Gjafakassar', 'snyrtivara', 7),
  ('snyrtivara--lyfjavara', 'Lyfjavara', 'snyrtivara', 8),
  ('dyrin', 'Dýrin', null, 200),
  ('dyrin--hundar', 'Hundar', 'dyrin', 1),
  ('dyrin--kettir', 'Kettir', 'dyrin', 2),
  ('dyrin--onnur-gaeludyr', 'Önnur gæludýr', 'dyrin', 3)
on conflict (slug) do update set name = excluded.name, parent_slug = excluded.parent_slug, sort = excluded.sort;
