-- VEFFLOKKAR v2 — HLÍÐARKAUPS-útgáfan: sami andi og hjá stóru keðjunum en EKKI eftirrit
-- (ósk Fannars 5.8.2026: "má ekki vera alveg nákvæmlega sama og Krónan, aðeins að breyta til").
-- Breytingar frá 790: Ávextir+Grænmeti sameinaðir, Heitir drykkir inn í Drykki, og eigin heiti:
-- Kjötborð, Bakarí, Álegg, Matargerð, Tilbúinn matur, Frosið, Nammi og nasl, Barnavörur,
-- Heimilið, Hreinlæti og snyrting, Gæludýr, Morgunverður og heilsa. 18 yfirflokkar.
-- Full endurskrift (ekkert var enn flokkað í framleiðslu þegar þetta keyrir).
set search_path = shop, public;

update shop.products set web_category = null where web_category is not null;
delete from shop.web_categories;

insert into shop.web_categories (slug, name, parent_slug, sort) values
  ('vinsaelar-vorur', 'Vinsælar vörur', null, 10),
  ('vinsaelar-vorur--mest-seldu-vorurnar', 'Mest seldu vörurnar', 'vinsaelar-vorur', 1),
  ('vinsaelar-vorur--tilbod-vikunnar', 'Tilboð vikunnar', 'vinsaelar-vorur', 2),
  ('vinsaelar-vorur--nyjar-vorur', 'Nýjar vörur', 'vinsaelar-vorur', 3),
  ('avextir-og-graenmeti', 'Ávextir og grænmeti', null, 20),
  ('avextir-og-graenmeti--bananar-epli-og-perur', 'Bananar, epli og perur', 'avextir-og-graenmeti', 1),
  ('avextir-og-graenmeti--ber-og-melonur', 'Ber og melónur', 'avextir-og-graenmeti', 2),
  ('avextir-og-graenmeti--sitrus-og-sudraenir-avextir', 'Sítrus og suðrænir ávextir', 'avextir-og-graenmeti', 3),
  ('avextir-og-graenmeti--kal-og-salat', 'Kál og salat', 'avextir-og-graenmeti', 4),
  ('avextir-og-graenmeti--kartoflur-og-rotargraenmeti', 'Kartöflur og rótargrænmeti', 'avextir-og-graenmeti', 5),
  ('avextir-og-graenmeti--tomatar-paprika-og-gurkur', 'Tómatar, paprika og gúrkur', 'avextir-og-graenmeti', 6),
  ('avextir-og-graenmeti--sveppir-og-laukur', 'Sveppir og laukur', 'avextir-og-graenmeti', 7),
  ('avextir-og-graenmeti--kryddjurtir', 'Kryddjurtir', 'avextir-og-graenmeti', 8),
  ('avextir-og-graenmeti--annad-graenmeti', 'Annað grænmeti', 'avextir-og-graenmeti', 9),
  ('kjotbord', 'Kjötborð', null, 30),
  ('kjotbord--lambakjot', 'Lambakjöt', 'kjotbord', 1),
  ('kjotbord--nautakjot', 'Nautakjöt', 'kjotbord', 2),
  ('kjotbord--svinakjot', 'Svínakjöt', 'kjotbord', 3),
  ('kjotbord--kjuklingur-og-kalkunn', 'Kjúklingur og kalkúnn', 'kjotbord', 4),
  ('kjotbord--hrossakjot', 'Hrossakjöt', 'kjotbord', 5),
  ('kjotbord--reykt-og-saltad-kjot', 'Reykt og saltað kjöt', 'kjotbord', 6),
  ('kjotbord--pylsur-og-bjugu', 'Pylsur og bjúgu', 'kjotbord', 7),
  ('kjotbord--slatur-og-thorramatur', 'Slátur og þorramatur', 'kjotbord', 8),
  ('kjotbord--hakk-og-fars', 'Hakk og fars', 'kjotbord', 9),
  ('fiskur-og-sjavarfang', 'Fiskur og sjávarfang', null, 40),
  ('fiskur-og-sjavarfang--ferskur-fiskur', 'Ferskur fiskur', 'fiskur-og-sjavarfang', 1),
  ('fiskur-og-sjavarfang--fiskrettir', 'Fiskréttir', 'fiskur-og-sjavarfang', 2),
  ('fiskur-og-sjavarfang--hardfiskur', 'Harðfiskur', 'fiskur-og-sjavarfang', 3),
  ('fiskur-og-sjavarfang--skelfiskur-og-humar', 'Skelfiskur og humar', 'fiskur-og-sjavarfang', 4),
  ('fiskur-og-sjavarfang--lax-og-silungur', 'Lax og silungur', 'fiskur-og-sjavarfang', 5),
  ('mjolk-ostar-og-egg', 'Mjólk, ostar og egg', null, 50),
  ('mjolk-ostar-og-egg--mjolk-og-rjomi', 'Mjólk og rjómi', 'mjolk-ostar-og-egg', 1),
  ('mjolk-ostar-og-egg--ostar', 'Ostar', 'mjolk-ostar-og-egg', 2),
  ('mjolk-ostar-og-egg--smjor-og-vidbit', 'Smjör og viðbit', 'mjolk-ostar-og-egg', 3),
  ('mjolk-ostar-og-egg--skyr-og-jogurt', 'Skyr og jógúrt', 'mjolk-ostar-og-egg', 4),
  ('mjolk-ostar-og-egg--jurtadrykkir', 'Jurtadrykkir', 'mjolk-ostar-og-egg', 5),
  ('mjolk-ostar-og-egg--egg', 'Egg', 'mjolk-ostar-og-egg', 6),
  ('mjolk-ostar-og-egg--kaldar-sosur-og-idyfur', 'Kaldar sósur og ídýfur', 'mjolk-ostar-og-egg', 7),
  ('bakari', 'Bakarí', null, 60),
  ('bakari--nybakad', 'Nýbakað', 'bakari', 1),
  ('bakari--braud', 'Brauð', 'bakari', 2),
  ('bakari--rugbraud-flatkokur-og-skonsur', 'Rúgbrauð, flatkökur og skonsur', 'bakari', 3),
  ('bakari--hamborgara-og-pylsubraud', 'Hamborgara- og pylsubrauð', 'bakari', 4),
  ('bakari--kokur-og-saetabraud', 'Kökur og sætabrauð', 'bakari', 5),
  ('bakari--kex-og-hrokkbraud', 'Kex og hrökkbrauð', 'bakari', 6),
  ('bakari--glutenlaust', 'Glútenlaust', 'bakari', 7),
  ('bakari--pizzabotnar-og-deig', 'Pizzabotnar og deig', 'bakari', 8),
  ('alegg', 'Álegg', null, 70),
  ('alegg--kjotalegg', 'Kjötálegg', 'alegg', 1),
  ('alegg--kaefa-og-pate', 'Kæfa og paté', 'alegg', 2),
  ('alegg--sild-og-kaviar', 'Síld og kavíar', 'alegg', 3),
  ('alegg--braudsalot', 'Brauðsalöt', 'alegg', 4),
  ('alegg--hnetusmjor-og-smuralegg', 'Hnetusmjör og smurálegg', 'alegg', 5),
  ('alegg--hummus', 'Hummus', 'alegg', 6),
  ('alegg--sulta-og-hunang', 'Sulta og hunang', 'alegg', 7),
  ('matargerd', 'Matargerð', null, 80),
  ('matargerd--pasta-og-italskt', 'Pasta og ítalskt', 'matargerd', 1),
  ('matargerd--asiskt', 'Asískt', 'matargerd', 2),
  ('matargerd--mexikoskt', 'Mexíkóskt', 'matargerd', 3),
  ('matargerd--hrisgrjon-og-grjon', 'Hrísgrjón og grjón', 'matargerd', 4),
  ('matargerd--oliur-og-edik', 'Olíur og edik', 'matargerd', 5),
  ('matargerd--baunir-og-nidursuduvorur', 'Baunir og niðursuðuvörur', 'matargerd', 6),
  ('matargerd--sosur-og-marineringar', 'Sósur og marineringar', 'matargerd', 7),
  ('matargerd--pakkasupur-og-sosur', 'Pakkasúpur og sósur', 'matargerd', 8),
  ('matargerd--krydd-og-kraftur', 'Krydd og kraftur', 'matargerd', 9),
  ('bakstur', 'Bakstur', null, 90),
  ('bakstur--hveiti-mjol-og-sykur', 'Hveiti, mjöl og sykur', 'bakstur', 1),
  ('bakstur--bokunarvorur', 'Bökunarvörur', 'bakstur', 2),
  ('bakstur--bokunarblondur-og-krem', 'Bökunarblöndur og krem', 'bakstur', 3),
  ('bakstur--dropar-og-bokunarkrydd', 'Dropar og bökunarkrydd', 'bakstur', 4),
  ('bakstur--bokunarpappir-og-form', 'Bökunarpappír og form', 'bakstur', 5),
  ('morgunverdur-og-heilsa', 'Morgunverður og heilsa', null, 100),
  ('morgunverdur-og-heilsa--morgunkorn-og-grautar', 'Morgunkorn og grautar', 'morgunverdur-og-heilsa', 1),
  ('morgunverdur-og-heilsa--hnetur-og-frae', 'Hnetur og fræ', 'morgunverdur-og-heilsa', 2),
  ('morgunverdur-og-heilsa--thurrkadir-avextir', 'Þurrkaðir ávextir', 'morgunverdur-og-heilsa', 3),
  ('morgunverdur-og-heilsa--vitamin-og-baetiefni', 'Vítamín og bætiefni', 'morgunverdur-og-heilsa', 4),
  ('morgunverdur-og-heilsa--orkustangir-og-skvisur', 'Orkustangir og skvísur', 'morgunverdur-og-heilsa', 5),
  ('tilbuinn-matur', 'Tilbúinn matur', null, 110),
  ('tilbuinn-matur--heitt-i-bordi', 'Heitt í borði', 'tilbuinn-matur', 1),
  ('tilbuinn-matur--grilladur-kjuklingur', 'Grillaður kjúklingur', 'tilbuinn-matur', 2),
  ('tilbuinn-matur--tilbunir-rettir', 'Tilbúnir réttir', 'tilbuinn-matur', 3),
  ('tilbuinn-matur--pizzur-og-pasta', 'Pizzur og pasta', 'tilbuinn-matur', 4),
  ('tilbuinn-matur--samlokur-og-vefjur', 'Samlokur og vefjur', 'tilbuinn-matur', 5),
  ('tilbuinn-matur--supur', 'Súpur', 'tilbuinn-matur', 6),
  ('frosid', 'Frosið', null, 120),
  ('frosid--frosid-graenmeti-og-avextir', 'Frosið grænmeti og ávextir', 'frosid', 1),
  ('frosid--frosid-braud-og-bakkelsi', 'Frosið brauð og bakkelsi', 'frosid', 2),
  ('frosid--franskar-og-kartofluvorur', 'Franskar og kartöfluvörur', 'frosid', 3),
  ('frosid--frosnir-rettir', 'Frosnir réttir', 'frosid', 4),
  ('frosid--frosid-kjot-og-sjavarfang', 'Frosið kjöt og sjávarfang', 'frosid', 5),
  ('frosid--is-og-eftirrettir', 'Ís og eftirréttir', 'frosid', 6),
  ('drykkir', 'Drykkir', null, 130),
  ('drykkir--gosdrykkir', 'Gosdrykkir', 'drykkir', 1),
  ('drykkir--vatn-og-kolsyrt-vatn', 'Vatn og kolsýrt vatn', 'drykkir', 2),
  ('drykkir--safar-og-theytingar', 'Safar og þeytingar', 'drykkir', 3),
  ('drykkir--orku-og-ithrottadrykkir', 'Orku- og íþróttadrykkir', 'drykkir', 4),
  ('drykkir--saft-og-thykkni', 'Saft og þykkni', 'drykkir', 5),
  ('drykkir--lettol-og-0', 'Léttöl og 0%', 'drykkir', 6),
  ('drykkir--kaffi', 'Kaffi', 'drykkir', 7),
  ('drykkir--te-og-kako', 'Te og kakó', 'drykkir', 8),
  ('nammi-og-nasl', 'Nammi og nasl', null, 140),
  ('nammi-og-nasl--saelgaeti', 'Sælgæti', 'nammi-og-nasl', 1),
  ('nammi-og-nasl--sukkuladi', 'Súkkulaði', 'nammi-og-nasl', 2),
  ('nammi-og-nasl--snakk', 'Snakk', 'nammi-og-nasl', 3),
  ('nammi-og-nasl--hnetur-og-nasl', 'Hnetur og nasl', 'nammi-og-nasl', 4),
  ('nammi-og-nasl--is-og-frostpinnar', 'Ís og frostpinnar', 'nammi-og-nasl', 5),
  ('barnavorur', 'Barnavörur', null, 150),
  ('barnavorur--barnamatur', 'Barnamatur', 'barnavorur', 1),
  ('barnavorur--bleiur-og-blautklutar', 'Bleiur og blautklútar', 'barnavorur', 2),
  ('barnavorur--barnasnyrtivorur', 'Barnasnyrtivörur', 'barnavorur', 3),
  ('barnavorur--leikfong', 'Leikföng', 'barnavorur', 4),
  ('heimilid', 'Heimilið', null, 160),
  ('heimilid--thvottaefni', 'Þvottaefni', 'heimilid', 1),
  ('heimilid--hreingerningavorur', 'Hreingerningavörur', 'heimilid', 2),
  ('heimilid--plast-al-og-pappir', 'Plast, ál og pappír', 'heimilid', 3),
  ('heimilid--bordbunadur-og-einnota', 'Borðbúnaður og einnota', 'heimilid', 4),
  ('heimilid--kerti-og-skreytingar', 'Kerti og skreytingar', 'heimilid', 5),
  ('heimilid--blom', 'Blóm', 'heimilid', 6),
  ('heimilid--rafhlodur-og-smahlutir', 'Rafhlöður og smáhlutir', 'heimilid', 7),
  ('hreinlaeti-og-snyrting', 'Hreinlæti og snyrting', null, 170),
  ('hreinlaeti-og-snyrting--harvorur', 'Hárvörur', 'hreinlaeti-og-snyrting', 1),
  ('hreinlaeti-og-snyrting--tannvorur', 'Tannvörur', 'hreinlaeti-og-snyrting', 2),
  ('hreinlaeti-og-snyrting--hudvorur', 'Húðvörur', 'hreinlaeti-og-snyrting', 3),
  ('hreinlaeti-og-snyrting--rakstur', 'Rakstur', 'hreinlaeti-og-snyrting', 4),
  ('hreinlaeti-og-snyrting--tidavorur', 'Tíðavörur', 'hreinlaeti-og-snyrting', 5),
  ('hreinlaeti-og-snyrting--sapur-og-sturtusapur', 'Sápur og sturtusápur', 'hreinlaeti-og-snyrting', 6),
  ('hreinlaeti-og-snyrting--lyfjavorur-og-plastrar', 'Lyfjavörur og plástrar', 'hreinlaeti-og-snyrting', 7),
  ('gaeludyr', 'Gæludýr', null, 180),
  ('gaeludyr--hundamatur-og-hundavorur', 'Hundamatur og hundavörur', 'gaeludyr', 1),
  ('gaeludyr--kattamatur-og-kattavorur', 'Kattamatur og kattavörur', 'gaeludyr', 2),
  ('gaeludyr--onnur-gaeludyr', 'Önnur gæludýr', 'gaeludyr', 3);
